plots:
- nodes/classical/ASEMD/metrics_dict.csv: {}
stages:
  classical_ASEGeoOpt:
    cmd: zntrack run ipsuite.nodes.ASEGeoOpt --name classical_ASEGeoOpt
    deps:
    - external/3398129b-a5e2-4708-94f1-3bdf887956c4.json
    - nodes/classical/Packmol_1/atoms.h5
    - nodes/classical/Packmol_1/node-meta.json
    - nodes/classical/Packmol_1/packmol
    metrics:
    - nodes/classical/ASEGeoOpt/node-meta.json:
        cache: false
    outs:
    - nodes/classical/ASEGeoOpt/model_outs
    - nodes/classical/ASEGeoOpt/trajectory.h5
    params:
    - classical_ASEGeoOpt
  classical_ASEMD:
    cmd: zntrack run ipsuite.nodes.ASEMD --name classical_ASEMD
    deps:
    - external/3398129b-a5e2-4708-94f1-3bdf887956c4.json
    - nodes/classical/ASEGeoOpt/model_outs
    - nodes/classical/ASEGeoOpt/node-meta.json
    - nodes/classical/ASEGeoOpt/trajectory.h5
    metrics:
    - nodes/classical/ASEMD/node-meta.json:
        cache: false
    - nodes/classical/ASEMD/steps_before_stopping.json:
        cache: false
    outs:
    - nodes/classical/ASEMD/metrics_dict.csv
    - nodes/classical/ASEMD/model
    - nodes/classical/ASEMD/trajectory.h5
    params:
    - classical_ASEMD
    - classical_ASEMD+thermostat
  classical_Packmol:
    cmd: zntrack run ipsuite.nodes.Packmol --name classical_Packmol
    deps:
    - nodes/classical/SmilesToAtoms/atoms.h5
    - nodes/classical/SmilesToAtoms/molecule.png
    - nodes/classical/SmilesToAtoms/node-meta.json
    - nodes/classical/SmilesToAtoms_1/atoms.h5
    - nodes/classical/SmilesToAtoms_1/molecule.png
    - nodes/classical/SmilesToAtoms_1/node-meta.json
    metrics:
    - nodes/classical/Packmol/node-meta.json:
        cache: false
    outs:
    - nodes/classical/Packmol/atoms.h5
    - nodes/classical/Packmol/packmol
    params:
    - classical_Packmol
  classical_Packmol_1:
    cmd: zntrack run ipsuite.nodes.Packmol --name classical_Packmol_1
    deps:
    - nodes/classical/Packmol/atoms.h5
    - nodes/classical/Packmol/node-meta.json
    - nodes/classical/Packmol/packmol
    metrics:
    - nodes/classical/Packmol_1/node-meta.json:
        cache: false
    outs:
    - nodes/classical/Packmol_1/atoms.h5
    - nodes/classical/Packmol_1/packmol
    params:
    - classical_Packmol_1
  classical_SmilesToAtoms:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name classical_SmilesToAtoms
    metrics:
    - nodes/classical/SmilesToAtoms/node-meta.json:
        cache: false
    outs:
    - nodes/classical/SmilesToAtoms/atoms.h5
    - nodes/classical/SmilesToAtoms/molecule.png
    params:
    - classical_SmilesToAtoms
  classical_SmilesToAtoms_1:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name classical_SmilesToAtoms_1
    metrics:
    - nodes/classical/SmilesToAtoms_1/node-meta.json:
        cache: false
    outs:
    - nodes/classical/SmilesToAtoms_1/atoms.h5
    - nodes/classical/SmilesToAtoms_1/molecule.png
    params:
    - classical_SmilesToAtoms_1
