plots:
- nodes/bootstrap/BoxScale/energies.csv:
    x: x
    x_label: Scale factor of the initial cell
    y: y
    y_label: predicted energy
stages:
  GeoOpt_ASEGeoOpt:
    cmd: zntrack run ipsuite.nodes.ASEGeoOpt --name GeoOpt_ASEGeoOpt
    deps:
    - nodes/GeoOpt/Packmol_1/atoms.h5
    - nodes/GeoOpt/Packmol_1/node-meta.json
    - nodes/GeoOpt/Packmol_1/packmol
    metrics:
    - nodes/GeoOpt/ASEGeoOpt/node-meta.json:
        cache: false
    outs:
    - nodes/GeoOpt/ASEGeoOpt/model_outs
    - nodes/GeoOpt/ASEGeoOpt/trajectory.h5
    params:
    - GeoOpt_ASEGeoOpt
    - config/cp2k.yaml: null
  GeoOpt_Packmol:
    cmd: zntrack run ipsuite.nodes.Packmol --name GeoOpt_Packmol
    deps:
    - nodes/GeoOpt/SmilesToAtoms/atoms.h5
    - nodes/GeoOpt/SmilesToAtoms/molecule.png
    - nodes/GeoOpt/SmilesToAtoms/node-meta.json
    - nodes/GeoOpt/SmilesToAtoms_1/atoms.h5
    - nodes/GeoOpt/SmilesToAtoms_1/molecule.png
    - nodes/GeoOpt/SmilesToAtoms_1/node-meta.json
    metrics:
    - nodes/GeoOpt/Packmol/node-meta.json:
        cache: false
    outs:
    - nodes/GeoOpt/Packmol/atoms.h5
    - nodes/GeoOpt/Packmol/packmol
    params:
    - GeoOpt_Packmol
  GeoOpt_Packmol_1:
    cmd: zntrack run ipsuite.nodes.Packmol --name GeoOpt_Packmol_1
    deps:
    - nodes/GeoOpt/Packmol/atoms.h5
    - nodes/GeoOpt/Packmol/node-meta.json
    - nodes/GeoOpt/Packmol/packmol
    metrics:
    - nodes/GeoOpt/Packmol_1/node-meta.json:
        cache: false
    outs:
    - nodes/GeoOpt/Packmol_1/atoms.h5
    - nodes/GeoOpt/Packmol_1/packmol
    params:
    - GeoOpt_Packmol_1
  GeoOpt_SmilesToAtoms:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name GeoOpt_SmilesToAtoms
    metrics:
    - nodes/GeoOpt/SmilesToAtoms/node-meta.json:
        cache: false
    outs:
    - nodes/GeoOpt/SmilesToAtoms/atoms.h5
    - nodes/GeoOpt/SmilesToAtoms/molecule.png
    params:
    - GeoOpt_SmilesToAtoms
  GeoOpt_SmilesToAtoms_1:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name GeoOpt_SmilesToAtoms_1
    metrics:
    - nodes/GeoOpt/SmilesToAtoms_1/node-meta.json:
        cache: false
    outs:
    - nodes/GeoOpt/SmilesToAtoms_1/atoms.h5
    - nodes/GeoOpt/SmilesToAtoms_1/molecule.png
    params:
    - GeoOpt_SmilesToAtoms_1
  bootstrap_BoxScale:
    cmd: zntrack run ipsuite.nodes.BoxScale --name bootstrap_BoxScale
    deps:
    - nodes/GeoOpt/ASEGeoOpt/model_outs
    - nodes/GeoOpt/ASEGeoOpt/node-meta.json
    - nodes/GeoOpt/ASEGeoOpt/trajectory.h5
    metrics:
    - nodes/bootstrap/BoxScale/node-meta.json:
        cache: false
    outs:
    - nodes/bootstrap/BoxScale/atoms.h5
    - nodes/bootstrap/BoxScale/energies.csv
    - nodes/bootstrap/BoxScale/energy.png
    - nodes/bootstrap/BoxScale/model
    params:
    - bootstrap_BoxScale
    - bootstrap_BoxScale+mapping
    - config/cp2k.yaml: null
  bootstrap_RotateMolecules:
    cmd: zntrack run ipsuite.nodes.RotateMolecules --name bootstrap_RotateMolecules
    deps:
    - nodes/GeoOpt/ASEGeoOpt/model_outs
    - nodes/GeoOpt/ASEGeoOpt/node-meta.json
    - nodes/GeoOpt/ASEGeoOpt/trajectory.h5
    metrics:
    - nodes/bootstrap/RotateMolecules/node-meta.json:
        cache: false
    outs:
    - nodes/bootstrap/RotateMolecules/atoms.h5
    - nodes/bootstrap/RotateMolecules/model_outs
    params:
    - bootstrap_RotateMolecules
    - config/cp2k.yaml: null
  bootstrap_TranslateMolecules:
    cmd: zntrack run ipsuite.nodes.TranslateMolecules --name bootstrap_TranslateMolecules
    deps:
    - nodes/GeoOpt/ASEGeoOpt/model_outs
    - nodes/GeoOpt/ASEGeoOpt/node-meta.json
    - nodes/GeoOpt/ASEGeoOpt/trajectory.h5
    metrics:
    - nodes/bootstrap/TranslateMolecules/node-meta.json:
        cache: false
    outs:
    - nodes/bootstrap/TranslateMolecules/atoms.h5
    - nodes/bootstrap/TranslateMolecules/model_outs
    params:
    - bootstrap_TranslateMolecules
    - config/cp2k.yaml: null
