plots:
- nodes/classical_ConfigurationSelection+kernel/similarities.csv: {}
stages:
  classical_AddData:
    cmd: zntrack run ipsuite.nodes.AddData --name classical_AddData
    deps:
    - data/nvt_eq.xyz
    metrics:
    - nodes/classical/AddData/node-meta.json:
        cache: false
    outs:
    - nodes/classical/AddData/atoms.h5
    params:
    - classical_AddData
  classical_ConfigurationSelection:
    cmd: zntrack run ipsuite.nodes.KernelSelection --name classical_ConfigurationSelection
    deps:
    - nodes/classical/AddData/atoms.h5
    - nodes/classical/AddData/node-meta.json
    metrics:
    - nodes/classical/ConfigurationSelection/node-meta.json:
        cache: false
    outs:
    - nodes/classical/ConfigurationSelection/kernel_results.json
    - nodes/classical/ConfigurationSelection/selected_configurations.json
    - nodes/classical/ConfigurationSelection/selection.png
    params:
    - classical_ConfigurationSelection
    - classical_ConfigurationSelection+kernel
  classical_CP2KSinglePoint:
    cmd: zntrack run ipsuite.nodes.CP2KSinglePoint --name classical_CP2KSinglePoint
    deps:
    - GTH_BASIS_SETS
    - GTH_POTENTIALS
    - dftd3.dat
    - nodes/classical/ConfigurationSelection/kernel_results.json
    - nodes/classical/ConfigurationSelection/node-meta.json
    - nodes/classical/ConfigurationSelection/selected_configurations.json
    - nodes/classical/ConfigurationSelection/selection.png
    params:
    - config/cp2k.yaml:
    outs:
    - nodes/classical/CP2KSinglePoint/atoms.h5
    - nodes/classical/CP2KSinglePoint/cp2k
    metrics:
    - nodes/classical/CP2KSinglePoint/node-meta.json:
        cache: false
