plots:
- nodes/ML0/MLModel/log.csv:
    template: dvc_plots/templates/y_log.json
    x: epoch
    x_label: epochs
    y: val_loss
    y_label: validation loss
- nodes/ML0/MLModel_1/log.csv:
    template: dvc_plots/templates/y_log.json
    x: epoch
    x_label: epochs
    y: val_loss
    y_label: validation loss
stages:
  ML0_MLModel:
    cmd: zntrack run ipsuite.nodes.Apax --name ML0_MLModel
    deps:
    - nodes/classical/ConfigurationSelection/node-meta.json
    - nodes/classical/ConfigurationSelection/selected_configurations.json
    - nodes/classical/ConfigurationSelection/selection.png
    metrics:
    - nodes/ML0/MLModel/metrics.json:
        cache: false
    - nodes/ML0/MLModel/node-meta.json:
        cache: false
    outs:
    - nodes/ML0/MLModel/apax_model
    - nodes/ML0/MLModel/log.csv
    - nodes/ML0/MLModel/train.log
    - nodes/ML0/MLModel/train_atoms.extxyz
    - nodes/ML0/MLModel/val_atoms.extxyz
    params:
    - ML0_MLModel
    - config/initial_model_1.yaml:
  ML0_MLModel_1:
    cmd: zntrack run ipsuite.nodes.Apax --name ML0_MLModel_1
    deps:
    - nodes/classical/ConfigurationSelection/node-meta.json
    - nodes/classical/ConfigurationSelection/selected_configurations.json
    - nodes/classical/ConfigurationSelection/selection.png
    metrics:
    - nodes/ML0/MLModel_1/metrics.json:
        cache: false
    - nodes/ML0/MLModel_1/node-meta.json:
        cache: false
    outs:
    - nodes/ML0/MLModel_1/apax_model
    - nodes/ML0/MLModel_1/log.csv
    - nodes/ML0/MLModel_1/train.log
    - nodes/ML0/MLModel_1/train_atoms.extxyz
    - nodes/ML0/MLModel_1/val_atoms.extxyz
    params:
    - ML0_MLModel_1
    - config/initial_model_2.yaml:
  classical_AddData:
    cmd: zntrack run ipsuite.nodes.AddData --name classical_AddData
    deps:
    - data/nvt_eq.xyz
    metrics:
    - nodes/classical/AddData/node-meta.json:
        cache: false
    outs:
    - nodes/classical/AddData/atoms.h5
    params:
    - classical_AddData
  classical_CP2KSinglePoint:
    cmd: zntrack run ipsuite.nodes.CP2KSinglePoint --name classical_CP2KSinglePoint
    deps:
    - GTH_BASIS_SETS
    - GTH_POTENTIALS
    - dftd3.dat
    - nodes/classical/AddData/atoms.h5
    - nodes/classical/AddData/node-meta.json
    metrics:
    - nodes/classical/CP2KSinglePoint/node-meta.json:
        cache: false
    outs:
    - nodes/classical/CP2KSinglePoint/atoms.h5
    - nodes/classical/CP2KSinglePoint/cp2k
    params:
    - config/cp2k.yaml:
  classical_ConfigurationSelection:
    cmd: zntrack run ipsuite.nodes.RandomSelection --name classical_ConfigurationSelection
    deps:
    - nodes/classical/CP2KSinglePoint/atoms.h5
    - nodes/classical/CP2KSinglePoint/cp2k
    - nodes/classical/CP2KSinglePoint/node-meta.json
    metrics:
    - nodes/classical/ConfigurationSelection/node-meta.json:
        cache: false
    outs:
    - nodes/classical/ConfigurationSelection/selected_configurations.json
    - nodes/classical/ConfigurationSelection/selection.png
    params:
    - classical_ConfigurationSelection
  ML0_ApaxEnsemble:
    cmd: zntrack run ipsuite.nodes.ApaxEnsemble --name ML0_ApaxEnsemble
    deps:
    - nodes/ML0/MLModel/apax_model
    - nodes/ML0/MLModel/log.csv
    - nodes/ML0/MLModel/metrics.json
    - nodes/ML0/MLModel/node-meta.json
    - nodes/ML0/MLModel/train.log
    - nodes/ML0/MLModel/train_atoms.extxyz
    - nodes/ML0/MLModel/val_atoms.extxyz
    - nodes/ML0/MLModel_1/apax_model
    - nodes/ML0/MLModel_1/log.csv
    - nodes/ML0/MLModel_1/metrics.json
    - nodes/ML0/MLModel_1/node-meta.json
    - nodes/ML0/MLModel_1/train.log
    - nodes/ML0/MLModel_1/train_atoms.extxyz
    - nodes/ML0/MLModel_1/val_atoms.extxyz
    metrics:
    - nodes/ML0/ApaxEnsemble/node-meta.json:
        cache: false
  ML0_Prediction:
    cmd: zntrack run ipsuite.nodes.Prediction --name ML0_Prediction
    deps:
    - nodes/ML0/ApaxEnsemble/node-meta.json
    - nodes/classical/ConfigurationSelection/node-meta.json
    - nodes/classical/ConfigurationSelection/selected_configurations.json
    - nodes/classical/ConfigurationSelection/selection.png
    outs:
    - nodes/ML0/Prediction/atoms.h5
    metrics:
    - nodes/ML0/Prediction/node-meta.json:
        cache: false
  ML0_PredictionMetrics:
    cmd: zntrack run ipsuite.nodes.PredictionMetrics --name ML0_PredictionMetrics
    deps:
    - nodes/ML0/Prediction/atoms.h5
    - nodes/ML0/Prediction/node-meta.json
    outs:
    - nodes/ML0/PredictionMetrics/energy_df.csv
    - nodes/ML0/PredictionMetrics/forces_df.csv
    - nodes/ML0/PredictionMetrics/plots
    - nodes/ML0/PredictionMetrics/stress_deviatoric_df.csv
    - nodes/ML0/PredictionMetrics/stress_df.csv
    - nodes/ML0/PredictionMetrics/stress_hydrostatic_df.csv
    metrics:
    - nodes/ML0/PredictionMetrics/deviat_stress.json:
        cache: false
    - nodes/ML0/PredictionMetrics/energy.json:
        cache: false
    - nodes/ML0/PredictionMetrics/forces.json:
        cache: false
    - nodes/ML0/PredictionMetrics/hydro_stress.json:
        cache: false
    - nodes/ML0/PredictionMetrics/node-meta.json:
        cache: false
    - nodes/ML0/PredictionMetrics/stress.json:
        cache: false
