plots:
- nodes/setup/ASEMD/metrics_dict.csv: {}
- nodes/setup/ASEMD_1/metrics_dict.csv: {}
- nodes/AIMD/ASEMD/metrics_dict.csv: {}
stages:
  AIMD_ASEMD:
    cmd: zntrack run ipsuite.nodes.ASEMD --name AIMD_ASEMD
    deps:
    - nodes/AIMD/CP2KSinglePoint/atoms.h5
    - nodes/AIMD/CP2KSinglePoint/cp2k
    - nodes/AIMD/CP2KSinglePoint/node-meta.json
    - nodes/setup/ASEMD_1/metrics_dict.csv
    - nodes/setup/ASEMD_1/model
    - nodes/setup/ASEMD_1/node-meta.json
    - nodes/setup/ASEMD_1/steps_before_stopping.json
    - nodes/setup/ASEMD_1/trajectory.h5
    metrics:
    - nodes/AIMD/ASEMD/node-meta.json:
        cache: false
    - nodes/AIMD/ASEMD/steps_before_stopping.json:
        cache: false
    outs:
    - nodes/AIMD/ASEMD/metrics_dict.csv
    - nodes/AIMD/ASEMD/model
    - nodes/AIMD/ASEMD/trajectory.h5
    params:
    - AIMD_ASEMD
    - AIMD_ASEMD+thermostat
  AIMD_CP2KSinglePoint:
    cmd: zntrack run ipsuite.nodes.CP2KSinglePoint --name AIMD_CP2KSinglePoint
    deps:
    - GTH_BASIS_SETS
    - GTH_POTENTIALS
    - nodes/AIMD/ConfigurationSelection/node-meta.json
    - nodes/AIMD/ConfigurationSelection/selected_configurations.json
    - nodes/AIMD/ConfigurationSelection/selection.png
    metrics:
    - nodes/AIMD/CP2KSinglePoint/node-meta.json:
        cache: false
    outs:
    - nodes/AIMD/CP2KSinglePoint/atoms.h5
    - nodes/AIMD/CP2KSinglePoint/cp2k
    params:
    - config/cp2k.yaml:
  AIMD_ConfigurationSelection:
    cmd: zntrack run ipsuite.nodes.IndexSelection --name AIMD_ConfigurationSelection
    deps:
    - nodes/setup/ASEMD_1/metrics_dict.csv
    - nodes/setup/ASEMD_1/model
    - nodes/setup/ASEMD_1/node-meta.json
    - nodes/setup/ASEMD_1/steps_before_stopping.json
    - nodes/setup/ASEMD_1/trajectory.h5
    metrics:
    - nodes/AIMD/ConfigurationSelection/node-meta.json:
        cache: false
    outs:
    - nodes/AIMD/ConfigurationSelection/selected_configurations.json
    - nodes/AIMD/ConfigurationSelection/selection.png
    params:
    - AIMD_ConfigurationSelection
  setup_ASEGeoOpt:
    cmd: zntrack run ipsuite.nodes.ASEGeoOpt --name setup_ASEGeoOpt
    deps:
    - external/7f8eaf10-9f5a-4471-80eb-356cbaedcff1.json
    - nodes/setup/Packmol_1/atoms.h5
    - nodes/setup/Packmol_1/node-meta.json
    - nodes/setup/Packmol_1/packmol
    metrics:
    - nodes/setup/ASEGeoOpt/node-meta.json:
        cache: false
    outs:
    - nodes/setup/ASEGeoOpt/model_outs
    - nodes/setup/ASEGeoOpt/trajectory.h5
    params:
    - setup_ASEGeoOpt
  setup_ASEMD:
    cmd: zntrack run ipsuite.nodes.ASEMD --name setup_ASEMD
    deps:
    - external/7f8eaf10-9f5a-4471-80eb-356cbaedcff1.json
    - nodes/setup/ASEGeoOpt/model_outs
    - nodes/setup/ASEGeoOpt/node-meta.json
    - nodes/setup/ASEGeoOpt/trajectory.h5
    metrics:
    - nodes/setup/ASEMD/node-meta.json:
        cache: false
    - nodes/setup/ASEMD/steps_before_stopping.json:
        cache: false
    outs:
    - nodes/setup/ASEMD/metrics_dict.csv
    - nodes/setup/ASEMD/model
    - nodes/setup/ASEMD/trajectory.h5
    params:
    - setup_ASEMD
    - setup_ASEMD+modifier+0
    - setup_ASEMD+thermostat
  setup_ASEMD_1:
    cmd: zntrack run ipsuite.nodes.ASEMD --name setup_ASEMD_1
    deps:
    - external/7f8eaf10-9f5a-4471-80eb-356cbaedcff1.json
    - nodes/setup/ASEMD/metrics_dict.csv
    - nodes/setup/ASEMD/model
    - nodes/setup/ASEMD/node-meta.json
    - nodes/setup/ASEMD/steps_before_stopping.json
    - nodes/setup/ASEMD/trajectory.h5
    metrics:
    - nodes/setup/ASEMD_1/node-meta.json:
        cache: false
    - nodes/setup/ASEMD_1/steps_before_stopping.json:
        cache: false
    outs:
    - nodes/setup/ASEMD_1/metrics_dict.csv
    - nodes/setup/ASEMD_1/model
    - nodes/setup/ASEMD_1/trajectory.h5
    params:
    - setup_ASEMD_1
    - setup_ASEMD_1+thermostat
  setup_Packmol:
    cmd: zntrack run ipsuite.nodes.Packmol --name setup_Packmol
    deps:
    - nodes/setup/SmilesToAtoms/atoms.h5
    - nodes/setup/SmilesToAtoms/molecule.png
    - nodes/setup/SmilesToAtoms/node-meta.json
    - nodes/setup/SmilesToAtoms_1/atoms.h5
    - nodes/setup/SmilesToAtoms_1/molecule.png
    - nodes/setup/SmilesToAtoms_1/node-meta.json
    metrics:
    - nodes/setup/Packmol/node-meta.json:
        cache: false
    outs:
    - nodes/setup/Packmol/atoms.h5
    - nodes/setup/Packmol/packmol
    params:
    - setup_Packmol
  setup_Packmol_1:
    cmd: zntrack run ipsuite.nodes.Packmol --name setup_Packmol_1
    deps:
    - nodes/setup/Packmol/atoms.h5
    - nodes/setup/Packmol/node-meta.json
    - nodes/setup/Packmol/packmol
    metrics:
    - nodes/setup/Packmol_1/node-meta.json:
        cache: false
    outs:
    - nodes/setup/Packmol_1/atoms.h5
    - nodes/setup/Packmol_1/packmol
    params:
    - setup_Packmol_1
  setup_SmilesToAtoms:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name setup_SmilesToAtoms
    metrics:
    - nodes/setup/SmilesToAtoms/node-meta.json:
        cache: false
    outs:
    - nodes/setup/SmilesToAtoms/atoms.h5
    - nodes/setup/SmilesToAtoms/molecule.png
    params:
    - setup_SmilesToAtoms
  setup_SmilesToAtoms_1:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name setup_SmilesToAtoms_1
    metrics:
    - nodes/setup/SmilesToAtoms_1/node-meta.json:
        cache: false
    outs:
    - nodes/setup/SmilesToAtoms_1/atoms.h5
    - nodes/setup/SmilesToAtoms_1/molecule.png
    params:
    - setup_SmilesToAtoms_1
