plots:
- nodes/classical/MLModel/log.csv:
    template: dvc_plots/templates/y_log.json
    x: epoch
    x_label: epochs
    y: val_loss
    y_label: validation loss
- nodes/ML0/MLModel/log.csv:
    template: dvc_plots/templates/y_log.json
    x: epoch
    x_label: epochs
    y: val_loss
    y_label: validation loss
- nodes/ML1/ASEMD/metrics_dict.csv: {}
stages:
  ML0_ConfigurationSelection:
    cmd: zntrack run ipsuite.nodes.BatchKernelSelection --name ML0_ConfigurationSelection
    deps:
    - nodes/classical/ConfigurationSelection_2/node-meta.json
    - nodes/classical/ConfigurationSelection_2/selected_configurations.json
    - nodes/classical/ConfigurationSelection_2/selection.png
    - nodes/classical/MLModel/apax_model
    - nodes/classical/MLModel/log.csv
    - nodes/classical/MLModel/metrics.json
    - nodes/classical/MLModel/node-meta.json
    - nodes/classical/MLModel/train.log
    - nodes/classical/MLModel/train_atoms.extxyz
    - nodes/classical/MLModel/val_atoms.extxyz
    metrics:
    - nodes/ML0/ConfigurationSelection/node-meta.json:
        cache: false
    outs:
    - nodes/ML0/ConfigurationSelection/selected_configurations.json
    - nodes/ML0/ConfigurationSelection/selection.png
    params:
    - ML0_ConfigurationSelection
  ML0_EnergyHistogram:
    cmd: zntrack run ipsuite.nodes.EnergyHistogram --name ML0_EnergyHistogram
    deps:
    - nodes/ML0/ConfigurationSelection/node-meta.json
    - nodes/ML0/ConfigurationSelection/selected_configurations.json
    - nodes/ML0/ConfigurationSelection/selection.png
    - nodes/classical/ConfigurationSelection_2/node-meta.json
    - nodes/classical/ConfigurationSelection_2/selected_configurations.json
    - nodes/classical/ConfigurationSelection_2/selection.png
    metrics:
    - nodes/ML0/EnergyHistogram/metrics.json:
        cache: false
    - nodes/ML0/EnergyHistogram/node-meta.json:
        cache: false
    outs:
    - nodes/ML0/EnergyHistogram/labels_df.csv
    - nodes/ML0/EnergyHistogram/plots
    params:
    - ML0_EnergyHistogram
  ML0_ForcesHistogram:
    cmd: zntrack run ipsuite.nodes.ForcesHistogram --name ML0_ForcesHistogram
    deps:
    - nodes/ML0/ConfigurationSelection/node-meta.json
    - nodes/ML0/ConfigurationSelection/selected_configurations.json
    - nodes/ML0/ConfigurationSelection/selection.png
    - nodes/classical/ConfigurationSelection_2/node-meta.json
    - nodes/classical/ConfigurationSelection_2/selected_configurations.json
    - nodes/classical/ConfigurationSelection_2/selection.png
    metrics:
    - nodes/ML0/ForcesHistogram/metrics.json:
        cache: false
    - nodes/ML0/ForcesHistogram/node-meta.json:
        cache: false
    outs:
    - nodes/ML0/ForcesHistogram/labels_df.csv
    - nodes/ML0/ForcesHistogram/plots
    params:
    - ML0_ForcesHistogram
  ML0_MLModel:
    cmd: zntrack run ipsuite.nodes.Apax --name ML0_MLModel
    deps:
    - nodes/ML0/ConfigurationSelection/node-meta.json
    - nodes/ML0/ConfigurationSelection/selected_configurations.json
    - nodes/ML0/ConfigurationSelection/selection.png
    - nodes/classical/ConfigurationSelection_1/node-meta.json
    - nodes/classical/ConfigurationSelection_1/selected_configurations.json
    - nodes/classical/ConfigurationSelection_1/selection.png
    - nodes/classical/ConfigurationSelection_2/node-meta.json
    - nodes/classical/ConfigurationSelection_2/selected_configurations.json
    - nodes/classical/ConfigurationSelection_2/selection.png
    metrics:
    - nodes/ML0/MLModel/metrics.json:
        cache: false
    - nodes/ML0/MLModel/node-meta.json:
        cache: false
    outs:
    - nodes/ML0/MLModel/apax_model
    - nodes/ML0/MLModel/log.csv
    - nodes/ML0/MLModel/train.log
    - nodes/ML0/MLModel/train_atoms.extxyz
    - nodes/ML0/MLModel/val_atoms.extxyz
    params:
    - ML0_MLModel
    - config/initial_model.yaml: null
  ML0_Prediction:
    cmd: zntrack run ipsuite.nodes.Prediction --name ML0_Prediction
    deps:
    - nodes/ML0/MLModel/apax_model
    - nodes/ML0/MLModel/log.csv
    - nodes/ML0/MLModel/metrics.json
    - nodes/ML0/MLModel/node-meta.json
    - nodes/ML0/MLModel/train.log
    - nodes/ML0/MLModel/train_atoms.extxyz
    - nodes/ML0/MLModel/val_atoms.extxyz
    - nodes/classical/ConfigurationSelection/node-meta.json
    - nodes/classical/ConfigurationSelection/selected_configurations.json
    - nodes/classical/ConfigurationSelection/selection.png
    metrics:
    - nodes/ML0/Prediction/node-meta.json:
        cache: false
    outs:
    - nodes/ML0/Prediction/atoms.h5
  ML0_PredictionMetrics:
    cmd: zntrack run ipsuite.nodes.PredictionMetrics --name ML0_PredictionMetrics
    deps:
    - nodes/ML0/Prediction/atoms.h5
    - nodes/ML0/Prediction/node-meta.json
    metrics:
    - nodes/ML0/PredictionMetrics/deviat_stress.json:
        cache: false
    - nodes/ML0/PredictionMetrics/energy.json:
        cache: false
    - nodes/ML0/PredictionMetrics/forces.json:
        cache: false
    - nodes/ML0/PredictionMetrics/hydro_stress.json:
        cache: false
    - nodes/ML0/PredictionMetrics/node-meta.json:
        cache: false
    - nodes/ML0/PredictionMetrics/stress.json:
        cache: false
    outs:
    - nodes/ML0/PredictionMetrics/energy_df.csv
    - nodes/ML0/PredictionMetrics/forces_df.csv
    - nodes/ML0/PredictionMetrics/plots
    - nodes/ML0/PredictionMetrics/stress_deviatoric_df.csv
    - nodes/ML0/PredictionMetrics/stress_df.csv
    - nodes/ML0/PredictionMetrics/stress_hydrostatic_df.csv
  ML1_ASEMD:
    cmd: zntrack run ipsuite.nodes.ASEMD --name ML1_ASEMD
    deps:
    - nodes/ML0/MLModel/apax_model
    - nodes/ML0/MLModel/log.csv
    - nodes/ML0/MLModel/metrics.json
    - nodes/ML0/MLModel/node-meta.json
    - nodes/ML0/MLModel/train.log
    - nodes/ML0/MLModel/train_atoms.extxyz
    - nodes/ML0/MLModel/val_atoms.extxyz
    - nodes/classical/AddData/atoms.h5
    - nodes/classical/AddData/node-meta.json
    metrics:
    - nodes/ML1/ASEMD/node-meta.json:
        cache: false
    - nodes/ML1/ASEMD/steps_before_stopping.json:
        cache: false
    outs:
    - nodes/ML1/ASEMD/metrics_dict.csv
    - nodes/ML1/ASEMD/model
    - nodes/ML1/ASEMD/trajectory.h5
    params:
    - ML1_ASEMD
    - ML1_ASEMD+checker_list+0
    - ML1_ASEMD+thermostat
  classical_ASEMD:
    cmd: zntrack run ipsuite.nodes.ASEMD --name classical_ASEMD
    deps:
    - nodes/classical/AddData/atoms.h5
    - nodes/classical/AddData/node-meta.json
    - nodes/classical/MLModel/apax_model
    - nodes/classical/MLModel/log.csv
    - nodes/classical/MLModel/metrics.json
    - nodes/classical/MLModel/node-meta.json
    - nodes/classical/MLModel/train.log
    - nodes/classical/MLModel/train_atoms.extxyz
    - nodes/classical/MLModel/val_atoms.extxyz
    metrics:
    - nodes/classical/ASEMD/node-meta.json:
        cache: false
    - nodes/classical/ASEMD/steps_before_stopping.json:
        cache: false
    outs:
    - nodes/classical/ASEMD/metrics_dict.csv
    - nodes/classical/ASEMD/model
    - nodes/classical/ASEMD/trajectory.h5
    params:
    - classical_ASEMD
    - classical_ASEMD+checker_list+0
    - classical_ASEMD+thermostat
  classical_AddData:
    cmd: zntrack run ipsuite.nodes.AddData --name classical_AddData
    deps:
    - data/nvt_eq.xyz
    metrics:
    - nodes/classical/AddData/node-meta.json:
        cache: false
    outs:
    - nodes/classical/AddData/atoms.h5
    params:
    - classical_AddData
  classical_CP2KSinglePoint:
    cmd: zntrack run ipsuite.nodes.CP2KSinglePoint --name classical_CP2KSinglePoint
    deps:
    - GTH_BASIS_SETS
    - GTH_POTENTIALS
    - dftd3.dat
    - nodes/classical/AddData/atoms.h5
    - nodes/classical/AddData/node-meta.json
    metrics:
    - nodes/classical/CP2KSinglePoint/node-meta.json:
        cache: false
    outs:
    - nodes/classical/CP2KSinglePoint/atoms.h5
    - nodes/classical/CP2KSinglePoint/cp2k
    params:
    - config/cp2k.yaml: null
  classical_ConfigurationSelection:
    cmd: zntrack run ipsuite.nodes.RandomSelection --name classical_ConfigurationSelection
    deps:
    - nodes/classical/FilterOutlier/filtered_indices.json
    - nodes/classical/FilterOutlier/histogram.png
    - nodes/classical/FilterOutlier/node-meta.json
    metrics:
    - nodes/classical/ConfigurationSelection/node-meta.json:
        cache: false
    outs:
    - nodes/classical/ConfigurationSelection/selected_configurations.json
    - nodes/classical/ConfigurationSelection/selection.png
    params:
    - classical_ConfigurationSelection
  classical_ConfigurationSelection_1:
    cmd: zntrack run ipsuite.nodes.RandomSelection --name classical_ConfigurationSelection_1
    deps:
    - nodes/classical/ConfigurationSelection/node-meta.json
    - nodes/classical/ConfigurationSelection/selected_configurations.json
    - nodes/classical/ConfigurationSelection/selection.png
    metrics:
    - nodes/classical/ConfigurationSelection_1/node-meta.json:
        cache: false
    outs:
    - nodes/classical/ConfigurationSelection_1/selected_configurations.json
    - nodes/classical/ConfigurationSelection_1/selection.png
    params:
    - classical_ConfigurationSelection_1
  classical_ConfigurationSelection_2:
    cmd: zntrack run ipsuite.nodes.RandomSelection --name classical_ConfigurationSelection_2
    deps:
    - nodes/classical/ConfigurationSelection_1/node-meta.json
    - nodes/classical/ConfigurationSelection_1/selected_configurations.json
    - nodes/classical/ConfigurationSelection_1/selection.png
    metrics:
    - nodes/classical/ConfigurationSelection_2/node-meta.json:
        cache: false
    outs:
    - nodes/classical/ConfigurationSelection_2/selected_configurations.json
    - nodes/classical/ConfigurationSelection_2/selection.png
    params:
    - classical_ConfigurationSelection_2
  classical_EnergyHistogram:
    cmd: zntrack run ipsuite.nodes.EnergyHistogram --name classical_EnergyHistogram
    deps:
    - nodes/classical/ConfigurationSelection_2/node-meta.json
    - nodes/classical/ConfigurationSelection_2/selected_configurations.json
    - nodes/classical/ConfigurationSelection_2/selection.png
    metrics:
    - nodes/classical/EnergyHistogram/metrics.json:
        cache: false
    - nodes/classical/EnergyHistogram/node-meta.json:
        cache: false
    outs:
    - nodes/classical/EnergyHistogram/labels_df.csv
    - nodes/classical/EnergyHistogram/plots
    params:
    - classical_EnergyHistogram
  classical_FilterOutlier:
    cmd: zntrack run ipsuite.nodes.FilterOutlier --name classical_FilterOutlier
    deps:
    - nodes/classical/CP2KSinglePoint/atoms.h5
    - nodes/classical/CP2KSinglePoint/cp2k
    - nodes/classical/CP2KSinglePoint/node-meta.json
    metrics:
    - nodes/classical/FilterOutlier/node-meta.json:
        cache: false
    outs:
    - nodes/classical/FilterOutlier/filtered_indices.json
    - nodes/classical/FilterOutlier/histogram.png
    params:
    - classical_FilterOutlier
  classical_ForcesHistogram:
    cmd: zntrack run ipsuite.nodes.ForcesHistogram --name classical_ForcesHistogram
    deps:
    - nodes/classical/ConfigurationSelection_2/node-meta.json
    - nodes/classical/ConfigurationSelection_2/selected_configurations.json
    - nodes/classical/ConfigurationSelection_2/selection.png
    metrics:
    - nodes/classical/ForcesHistogram/metrics.json:
        cache: false
    - nodes/classical/ForcesHistogram/node-meta.json:
        cache: false
    outs:
    - nodes/classical/ForcesHistogram/labels_df.csv
    - nodes/classical/ForcesHistogram/plots
    params:
    - classical_ForcesHistogram
  classical_MLModel:
    cmd: zntrack run ipsuite.nodes.Apax --name classical_MLModel
    deps:
    - nodes/classical/ConfigurationSelection_1/node-meta.json
    - nodes/classical/ConfigurationSelection_1/selected_configurations.json
    - nodes/classical/ConfigurationSelection_1/selection.png
    - nodes/classical/ConfigurationSelection_2/node-meta.json
    - nodes/classical/ConfigurationSelection_2/selected_configurations.json
    - nodes/classical/ConfigurationSelection_2/selection.png
    metrics:
    - nodes/classical/MLModel/metrics.json:
        cache: false
    - nodes/classical/MLModel/node-meta.json:
        cache: false
    outs:
    - nodes/classical/MLModel/apax_model
    - nodes/classical/MLModel/log.csv
    - nodes/classical/MLModel/train.log
    - nodes/classical/MLModel/train_atoms.extxyz
    - nodes/classical/MLModel/val_atoms.extxyz
    params:
    - classical_MLModel
    - config/initial_model.yaml: null
  classical_Prediction:
    cmd: zntrack run ipsuite.nodes.Prediction --name classical_Prediction
    deps:
    - nodes/classical/ConfigurationSelection/node-meta.json
    - nodes/classical/ConfigurationSelection/selected_configurations.json
    - nodes/classical/ConfigurationSelection/selection.png
    - nodes/classical/MLModel/apax_model
    - nodes/classical/MLModel/log.csv
    - nodes/classical/MLModel/metrics.json
    - nodes/classical/MLModel/node-meta.json
    - nodes/classical/MLModel/train.log
    - nodes/classical/MLModel/train_atoms.extxyz
    - nodes/classical/MLModel/val_atoms.extxyz
    metrics:
    - nodes/classical/Prediction/node-meta.json:
        cache: false
    outs:
    - nodes/classical/Prediction/atoms.h5
  classical_PredictionMetrics:
    cmd: zntrack run ipsuite.nodes.PredictionMetrics --name classical_PredictionMetrics
    deps:
    - nodes/classical/Prediction/atoms.h5
    - nodes/classical/Prediction/node-meta.json
    metrics:
    - nodes/classical/PredictionMetrics/deviat_stress.json:
        cache: false
    - nodes/classical/PredictionMetrics/energy.json:
        cache: false
    - nodes/classical/PredictionMetrics/forces.json:
        cache: false
    - nodes/classical/PredictionMetrics/hydro_stress.json:
        cache: false
    - nodes/classical/PredictionMetrics/node-meta.json:
        cache: false
    - nodes/classical/PredictionMetrics/stress.json:
        cache: false
    outs:
    - nodes/classical/PredictionMetrics/energy_df.csv
    - nodes/classical/PredictionMetrics/forces_df.csv
    - nodes/classical/PredictionMetrics/plots
    - nodes/classical/PredictionMetrics/stress_deviatoric_df.csv
    - nodes/classical/PredictionMetrics/stress_df.csv
    - nodes/classical/PredictionMetrics/stress_hydrostatic_df.csv
