plots:
- nodes/classical/MLModel/log.csv:
    template: dvc_plots/templates/y_log.json
    x: epoch
    x_label: epochs
    y: val_loss
    y_label: validation loss
- nodes/ML0/ASEMD/metrics_dict.csv: {}
stages:
  ML0_ASEMD:
    cmd: zntrack run ipsuite.nodes.ASEMD --name ML0_ASEMD
    deps:
    - nodes/classical/AddData/atoms.h5
    - nodes/classical/AddData/node-meta.json
    - nodes/classical/MLModel/apax_model
    - nodes/classical/MLModel/log.csv
    - nodes/classical/MLModel/metrics.json
    - nodes/classical/MLModel/node-meta.json
    - nodes/classical/MLModel/train.log
    - nodes/classical/MLModel/train_atoms.extxyz
    - nodes/classical/MLModel/val_atoms.extxyz
    metrics:
    - nodes/ML0/ASEMD/node-meta.json:
        cache: false
    - nodes/ML0/ASEMD/steps_before_stopping.json:
        cache: false
    outs:
    - nodes/ML0/ASEMD/metrics_dict.csv
    - nodes/ML0/ASEMD/model
    - nodes/ML0/ASEMD/trajectory.h5
    params:
    - ML0_ASEMD
    - ML0_ASEMD+checker_list+0
    - ML0_ASEMD+thermostat
  classical_AddData:
    cmd: zntrack run ipsuite.nodes.AddData --name classical_AddData
    deps:
    - data/nvt_eq.xyz
    metrics:
    - nodes/classical/AddData/node-meta.json:
        cache: false
    outs:
    - nodes/classical/AddData/atoms.h5
    params:
    - classical_AddData
  classical_CP2KSinglePoint:
    cmd: zntrack run ipsuite.nodes.CP2KSinglePoint --name classical_CP2KSinglePoint
    deps:
    - GTH_BASIS_SETS
    - GTH_POTENTIALS
    - dftd3.dat
    - nodes/classical/AddData/atoms.h5
    - nodes/classical/AddData/node-meta.json
    metrics:
    - nodes/classical/CP2KSinglePoint/node-meta.json:
        cache: false
    outs:
    - nodes/classical/CP2KSinglePoint/atoms.h5
    - nodes/classical/CP2KSinglePoint/cp2k
    params:
    - config/cp2k.yaml: null
  classical_ConfigurationSelection:
    cmd: zntrack run ipsuite.nodes.RandomSelection --name classical_ConfigurationSelection
    deps:
    - nodes/classical/FilterOutlier/filtered_indices.json
    - nodes/classical/FilterOutlier/histogram.png
    - nodes/classical/FilterOutlier/node-meta.json
    metrics:
    - nodes/classical/ConfigurationSelection/node-meta.json:
        cache: false
    outs:
    - nodes/classical/ConfigurationSelection/selected_configurations.json
    - nodes/classical/ConfigurationSelection/selection.png
    params:
    - classical_ConfigurationSelection
  classical_ConfigurationSelection_1:
    cmd: zntrack run ipsuite.nodes.RandomSelection --name classical_ConfigurationSelection_1
    deps:
    - nodes/classical/ConfigurationSelection/node-meta.json
    - nodes/classical/ConfigurationSelection/selected_configurations.json
    - nodes/classical/ConfigurationSelection/selection.png
    metrics:
    - nodes/classical/ConfigurationSelection_1/node-meta.json:
        cache: false
    outs:
    - nodes/classical/ConfigurationSelection_1/selected_configurations.json
    - nodes/classical/ConfigurationSelection_1/selection.png
    params:
    - classical_ConfigurationSelection_1
  classical_FilterOutlier:
    cmd: zntrack run ipsuite.nodes.FilterOutlier --name classical_FilterOutlier
    deps:
    - nodes/classical/CP2KSinglePoint/atoms.h5
    - nodes/classical/CP2KSinglePoint/cp2k
    - nodes/classical/CP2KSinglePoint/node-meta.json
    metrics:
    - nodes/classical/FilterOutlier/node-meta.json:
        cache: false
    outs:
    - nodes/classical/FilterOutlier/filtered_indices.json
    - nodes/classical/FilterOutlier/histogram.png
    params:
    - classical_FilterOutlier
  classical_MLModel:
    cmd: zntrack run ipsuite.nodes.Apax --name classical_MLModel
    deps:
    - nodes/classical/ConfigurationSelection/node-meta.json
    - nodes/classical/ConfigurationSelection/selected_configurations.json
    - nodes/classical/ConfigurationSelection/selection.png
    - nodes/classical/ConfigurationSelection_1/node-meta.json
    - nodes/classical/ConfigurationSelection_1/selected_configurations.json
    - nodes/classical/ConfigurationSelection_1/selection.png
    metrics:
    - nodes/classical/MLModel/metrics.json:
        cache: false
    - nodes/classical/MLModel/node-meta.json:
        cache: false
    outs:
    - nodes/classical/MLModel/apax_model
    - nodes/classical/MLModel/log.csv
    - nodes/classical/MLModel/train.log
    - nodes/classical/MLModel/train_atoms.extxyz
    - nodes/classical/MLModel/val_atoms.extxyz
    params:
    - classical_MLModel
    - config/initial_model.yaml: null
  classical_Prediction:
    cmd: zntrack run ipsuite.nodes.Prediction --name classical_Prediction
    deps:
    - nodes/classical/ConfigurationSelection_1/node-meta.json
    - nodes/classical/ConfigurationSelection_1/selected_configurations.json
    - nodes/classical/ConfigurationSelection_1/selection.png
    - nodes/classical/MLModel/apax_model
    - nodes/classical/MLModel/log.csv
    - nodes/classical/MLModel/metrics.json
    - nodes/classical/MLModel/node-meta.json
    - nodes/classical/MLModel/train.log
    - nodes/classical/MLModel/train_atoms.extxyz
    - nodes/classical/MLModel/val_atoms.extxyz
    metrics:
    - nodes/classical/Prediction/node-meta.json:
        cache: false
    outs:
    - nodes/classical/Prediction/atoms.h5
  classical_PredictionMetrics:
    cmd: zntrack run ipsuite.nodes.PredictionMetrics --name classical_PredictionMetrics
    deps:
    - nodes/classical/Prediction/atoms.h5
    - nodes/classical/Prediction/node-meta.json
    metrics:
    - nodes/classical/PredictionMetrics/deviat_stress.json:
        cache: false
    - nodes/classical/PredictionMetrics/energy.json:
        cache: false
    - nodes/classical/PredictionMetrics/forces.json:
        cache: false
    - nodes/classical/PredictionMetrics/hydro_stress.json:
        cache: false
    - nodes/classical/PredictionMetrics/node-meta.json:
        cache: false
    - nodes/classical/PredictionMetrics/stress.json:
        cache: false
    outs:
    - nodes/classical/PredictionMetrics/energy_df.csv
    - nodes/classical/PredictionMetrics/forces_df.csv
    - nodes/classical/PredictionMetrics/plots
    - nodes/classical/PredictionMetrics/stress_deviatoric_df.csv
    - nodes/classical/PredictionMetrics/stress_df.csv
    - nodes/classical/PredictionMetrics/stress_hydrostatic_df.csv
