stages:
  classical_AddData:
    cmd: zntrack run ipsuite.nodes.AddData --name classical_AddData
    deps:
    - data/nvt_eq.xyz
    params:
    - classical_AddData
    outs:
    - nodes/classical/AddData/atoms.h5
    metrics:
    - nodes/classical/AddData/node-meta.json:
        cache: false
  classical_CP2KSinglePoint:
    cmd: zntrack run ipsuite.nodes.CP2KSinglePoint --name classical_CP2KSinglePoint
    deps:
    - GTH_BASIS_SETS
    - GTH_POTENTIALS
    - dftd3.dat
    - nodes/classical/AddData/atoms.h5
    - nodes/classical/AddData/node-meta.json
    params:
    - config/cp2k.yaml:
    outs:
    - nodes/classical/CP2KSinglePoint/atoms.h5
    - nodes/classical/CP2KSinglePoint/cp2k
    metrics:
    - nodes/classical/CP2KSinglePoint/node-meta.json:
        cache: false
