depl_ASEGeoOpt:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: FIRE
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.05
depl_ASEMD:
    data_id: -1
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 10
    seed: 42
    steps: 10000
    use_momenta: false
    wrap: false
depl_ASEMD+modifier+0:
    cell: null
    density: 1162
depl_ASEMD+thermostat:
    friction: 0.01
    temperature: 353
    time_step: 0.5
depl_ASEMD_1:
    data_id: -1
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 10
    seed: 42
    steps: 10000
    use_momenta: false
    wrap: false
depl_ASEMD_1+thermostat:
    friction: 0.01
    temperature: 353
    time_step: 0.5
depl_Packmol:
    box: null
    count:
    - 1
    - 1
    data_ids: null
    density: 1210
    pbc: false
    tolerance: 2.0
depl_Packmol_1:
    box: null
    count:
    - 16
    data_ids: null
    density: 900
    pbc: true
    tolerance: 2.0
depl_SmilesToAtoms:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: '[B-](F)(F)(F)F'
depl_SmilesToAtoms_1:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: CCCCN1C=C[N+](=C1)C
