GeoOpt_ASEGeoOpt:
    data_id: 0
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.1
GeoOpt_Packmol:
    box: null
    count:
    - 1
    - 1
    data_ids: null
    density: 1210
    tolerance: 2.0
GeoOpt_Packmol_1:
    box: null
    count:
    - 10
    data_ids: null
    density: 1210
    tolerance: 2.0
GeoOpt_SmilesToAtoms:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: CCCCN1C=C[N+](=C1)C
GeoOpt_SmilesToAtoms_1:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: '[B-](F)(F)(F)F'
MD_ASEMD:
    data_id: -1
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    seed: 42
    steps: 50000
    use_momenta: false
MD_ASEMD+checker_list+0:
    larger_only: false
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: forces
    window_size: 500
MD_ASEMD+thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
MD_ConfigurationSelection:
    correlation_time: 1
    n_configurations: 20
    points_per_cycle: 1
    seed: 1234
    threshold: 0.99
MD_ConfigurationSelection+kernel:
    memory: 1000
    soap:
        _type: soap_parameter_dataclass
        value:
            l_max: 5
            n_jobs: -1
            n_max: 7
            r_cut: 6.0
            rbf: gto
            sigma: 0.5
            weighting: null
ML0_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
ML0_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
ML0_MMK:
    correlation_time: 1
    n_configurations: 20
    points_per_cycle: 1
    seed: 1234
    threshold: 0.99
ML0_MMK+kernel:
    memory: 1000
    soap:
        _type: soap_parameter_dataclass
        value:
            l_max: 5
            n_jobs: -1
            n_max: 7
            r_cut: 6.0
            rbf: gto
            sigma: 0.5
            weighting: null
bootstrap_ConfigurationSelection:
    correlation_time: 1
    n_configurations: 50
    points_per_cycle: 1
    seed: 1234
    threshold: 0.99
bootstrap_ConfigurationSelection+kernel:
    memory: 1000
    soap:
        _type: soap_parameter_dataclass
        value:
            l_max: 5
            n_jobs: -1
            n_max: 7
            r_cut: 6.0
            rbf: gto
            sigma: 0.5
            weighting: null
bootstrap_RotateMolecules:
    data_id: -1
    include_original: false
    maximum: 0.17452777777777778
    n_configurations: 500
    seed: 1
bootstrap_TranslateMolecules:
    data_id: -1
    include_original: false
    maximum: 0.2
    n_configurations: 500
    seed: 1
