GeoOpt_ASEGeoOpt:
    data_id: 0
    dump_rate: 100
    init_kwargs: {}
    optimizer: FIRE
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.1
GeoOpt_Packmol:
    box: null
    count:
    - 1
    - 1
    data_ids: null
    density: 1210
    tolerance: 2.0
GeoOpt_Packmol_1:
    box: null
    count:
    - 2
    data_ids: null
    density: 1210
    tolerance: 2.0
GeoOpt_SmilesToAtoms:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: CCCCN1C=C[N+](=C1)C
GeoOpt_SmilesToAtoms_1:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: '[B-](F)(F)(F)F'
ML0_ASEMD:
    data_id: -1
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    seed: 42
    steps: 50000
    use_momenta: false
    wrap: false
ML0_ASEMD+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 0.5
    minimum_window_size: 1
    value: forces_uncertainty
    window_size: 500
ML0_ASEMD+thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
ML0_ConfigurationSelection:
    dim_reduction: max
    key: forces_uncertainty
    min_distance: 5
    n_configurations: 20
    reduction_axis:
    - 1
    - 2
    reference: energy
    threshold: null
ML0_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
ML0_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
ML1_ASEMD:
    data_id: -1
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    seed: 42
    steps: 50000
    use_momenta: false
    wrap: false
ML1_ASEMD+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 0.5
    minimum_window_size: 1
    value: forces_uncertainty
    window_size: 500
ML1_ASEMD+thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
ML1_ConfigurationSelection:
    dim_reduction: max
    key: forces_uncertainty
    min_distance: 5
    n_configurations: 20
    reduction_axis:
    - 1
    - 2
    reference: energy
    threshold: null
ML1_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
ML1_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
ML2_ASEMD:
    data_id: -1
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    seed: 42
    steps: 50000
    use_momenta: false
    wrap: false
ML2_ASEMD+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 0.5
    minimum_window_size: 1
    value: forces_uncertainty
    window_size: 500
ML2_ASEMD+thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
ML2_ConfigurationSelection:
    dim_reduction: max
    key: forces_uncertainty
    min_distance: 50
    n_configurations: 50
    reduction_axis:
    - 1
    - 2
    reference: energy
    threshold: null
ML2_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
ML2_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
ML3_ASEMD:
    data_id: -1
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    seed: 42
    steps: 50000
    use_momenta: false
    wrap: false
ML3_ASEMD+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 0.5
    minimum_window_size: 1
    value: forces_uncertainty
    window_size: 500
ML3_ASEMD+thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
ML3_ConfigurationSelection:
    dim_reduction: max
    key: forces_uncertainty
    min_distance: 50
    n_configurations: 50
    reduction_axis:
    - 1
    - 2
    reference: energy
    threshold: null
ML3_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
ML3_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
classical_AddData:
    lines_to_read: null
classical_ConfigurationSelection:
    n_configurations: 1000
    seed: 1234
