GeoOpt_ASEGeoOpt:
    data_id: 0
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.1
GeoOpt_Packmol:
    box: null
    count:
    - 1
    - 1
    data_ids: null
    density: 1210
    tolerance: 2.0
GeoOpt_Packmol_1:
    box: null
    count:
    - 10
    data_ids: null
    density: 1210
    tolerance: 2.0
GeoOpt_SmilesToAtoms:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: CCCCN1C=C[N+](=C1)C
GeoOpt_SmilesToAtoms_1:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: '[B-](F)(F)(F)F'
bootstrap_RattleAtoms:
    data_id: -1
    include_original: false
    maximum: 0.1
    n_configurations: 15
    seed: 1
bootstrap_RotateMolecules:
    data_id: -1
    include_original: false
    maximum: 0.08726388888888889
    n_configurations: 15
    seed: 1
bootstrap_TranslateMolecules:
    data_id: -1
    include_original: false
    maximum: 0.1
    n_configurations: 15
    seed: 1
initial_model_ConfigurationSelection:
    n_configurations: 30
    seed: 1234
initial_model_ConfigurationSelection_1:
    indices:
        _type: slice
        value:
            start: 10
            step: null
            stop: null
initial_model_ConfigurationSelection_2:
    n_configurations: 50
    seed: 1234
initial_model_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
initial_model_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
