ML0_ConfigurationSelection:
    base_feature_map:
        layer_name: dense_2
        name: ll_grad
    n_configurations: 400
    selection_method: max_dist
ML0_EnergyHistogram:
    bins: 100
    x_lim: null
    y_lim: null
ML0_ForcesHistogram:
    bins: null
    x_lim: null
    y_lim: null
ML0_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
ML1_ASEGeoOpt:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: FIRE
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
ML1_ASEMD:
    data_id: -1
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 10
    seed: 42
    steps: 50000
    use_momenta: false
    wrap: false
ML1_ASEMD+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 0.5
    minimum_window_size: 1
    value: forces_uncertainty
    window_size: 500
ML1_ASEMD+thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
ML1_ConfigurationSelection:
    base_feature_map:
        layer_name: dense_2
        name: ll_grad
    n_configurations: 50
    selection_method: max_dist
ML1_EnergyHistogram:
    bins: 100
    x_lim: null
    y_lim: null
ML1_ForcesHistogram:
    bins: null
    x_lim: null
    y_lim: null
ML1_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
ML2_ASEGeoOpt:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: FIRE
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
ML2_ASEMD:
    data_id: -1
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 10
    seed: 42
    steps: 50000
    use_momenta: false
    wrap: false
ML2_ASEMD+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 0.5
    minimum_window_size: 1
    value: forces_uncertainty
    window_size: 500
ML2_ASEMD+thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
ML2_ConfigurationSelection:
    base_feature_map:
        layer_name: dense_2
        name: ll_grad
    n_configurations: 50
    selection_method: max_dist
ML2_EnergyHistogram:
    bins: 100
    x_lim: null
    y_lim: null
ML2_ForcesHistogram:
    bins: null
    x_lim: null
    y_lim: null
ML2_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
ML3_ASEGeoOpt:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: FIRE
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
ML3_ASEMD:
    data_id: -1
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 10
    seed: 42
    steps: 50000
    use_momenta: false
    wrap: false
ML3_ASEMD+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 0.5
    minimum_window_size: 1
    value: forces_uncertainty
    window_size: 500
ML3_ASEMD+thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
ML3_ConfigurationSelection:
    base_feature_map:
        layer_name: dense_2
        name: ll_grad
    n_configurations: 50
    selection_method: max_dist
ML3_EnergyHistogram:
    bins: 100
    x_lim: null
    y_lim: null
ML3_ForcesHistogram:
    bins: null
    x_lim: null
    y_lim: null
ML3_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
ML4_ASEGeoOpt:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: FIRE
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
ML4_ASEMD:
    data_id: -1
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 10
    seed: 42
    steps: 50000
    use_momenta: false
    wrap: false
ML4_ASEMD+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 0.5
    minimum_window_size: 1
    value: forces_uncertainty
    window_size: 500
ML4_ASEMD+thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
ML4_ConfigurationSelection:
    base_feature_map:
        layer_name: dense_2
        name: ll_grad
    n_configurations: 50
    selection_method: max_dist
ML4_EnergyHistogram:
    bins: 100
    x_lim: null
    y_lim: null
ML4_ForcesHistogram:
    bins: null
    x_lim: null
    y_lim: null
ML4_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
ML5_ASEGeoOpt:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: FIRE
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
ML5_ASEMD:
    data_id: -1
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 10
    seed: 42
    steps: 50000
    use_momenta: false
    wrap: false
ML5_ASEMD+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 0.5
    minimum_window_size: 1
    value: forces_uncertainty
    window_size: 500
ML5_ASEMD+modifier+0:
    end_temperature: 500
    interval: 1
    num_oscillations: 10
    start_temperature: 230
    temperature_amplitude: 150
ML5_ASEMD+thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
ML5_ConfigurationSelection:
    base_feature_map:
        layer_name: dense_2
        name: ll_grad
    n_configurations: 50
    selection_method: max_dist
ML5_EnergyHistogram:
    bins: 100
    x_lim: null
    y_lim: null
ML5_ForcesHistogram:
    bins: null
    x_lim: null
    y_lim: null
ML5_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
ML6_ASEGeoOpt:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: FIRE
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
ML6_ASEMD:
    data_id: -1
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 10
    seed: 42
    steps: 50000
    use_momenta: false
    wrap: false
ML6_ASEMD+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 0.5
    minimum_window_size: 1
    value: forces_uncertainty
    window_size: 500
ML6_ASEMD+modifier+0:
    end_temperature: 500
    interval: 1
    num_oscillations: 10
    start_temperature: 230
    temperature_amplitude: 150
ML6_ASEMD+thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
ML6_ConfigurationSelection:
    base_feature_map:
        layer_name: dense_2
        name: ll_grad
    n_configurations: 50
    selection_method: max_dist
classical_ASEMD:
    data_id: -1
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 10
    seed: 42
    steps: 50000
    use_momenta: false
    wrap: false
classical_ASEMD+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 0.5
    minimum_window_size: 1
    value: forces_uncertainty
    window_size: 500
classical_ASEMD+thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
classical_AddData:
    lines_to_read: null
classical_ConfigurationSelection:
    n_configurations: 500
    seed: 1234
classical_ConfigurationSelection_1:
    n_configurations: 100
    seed: 1234
classical_ConfigurationSelection_2:
    n_configurations: 100
    seed: 1234
classical_EnergyHistogram:
    bins: 100
    x_lim: null
    y_lim: null
classical_FilterOutlier:
    direction: both
    key: energy
    threshold: 3
classical_ForcesHistogram:
    bins: null
    x_lim: null
    y_lim: null
classical_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
