AL0_model_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL0_model_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL0_test_ASEGeoOpt:
    data_id: -5
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
AL0_test_ASEGeoOpt+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL0_test_ASEGeoOpt_1:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
AL0_test_ASEMD:
    data_id: -10
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    steps: 100000
    use_momenta: false
AL0_test_ASEMD+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL0_test_ASEMD+thermostat:
    friction: 0.01
    temperature: 293
    time_step: 0.5
AL0_test_ConfigurationSelection:
    indices:
        _type: slice
        value:
            start: 0
            step: null
            stop: -1
AL0_test_ConfigurationSelection_1:
    n_configurations: 5
    seed: 1234
AL0_train_ASEGeoOpt:
    data_id: -5
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
AL0_train_ASEGeoOpt+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL0_train_ASEGeoOpt_1:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
AL0_train_ASEMD:
    data_id: -1
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    steps: 100000
    use_momenta: false
AL0_train_ASEMD+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL0_train_ASEMD+thermostat:
    friction: 0.01
    temperature: 293
    time_step: 0.5
AL0_train_ConfigurationSelection:
    indices:
        _type: slice
        value:
            start: 0
            step: null
            stop: -1
AL0_train_ConfigurationSelection_1:
    n_configurations: 15
    seed: 1234
AL1_model_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL1_model_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL1_test_ASEGeoOpt:
    data_id: -5
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
AL1_test_ASEGeoOpt+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL1_test_ASEGeoOpt_1:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
AL1_test_ASEMD:
    data_id: -1
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    steps: 100000
    use_momenta: false
AL1_test_ASEMD+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL1_test_ASEMD+thermostat:
    friction: 0.01
    temperature: 293
    time_step: 0.5
AL1_test_ConfigurationSelection:
    indices:
        _type: slice
        value:
            start: 0
            step: null
            stop: -1
AL1_test_ConfigurationSelection_1:
    n_configurations: 5
    seed: 1234
AL1_train_ASEGeoOpt:
    data_id: -5
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
AL1_train_ASEGeoOpt+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL1_train_ASEGeoOpt_1:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
AL1_train_ASEMD:
    data_id: -1
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    steps: 100000
    use_momenta: false
AL1_train_ASEMD+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL1_train_ASEMD+thermostat:
    friction: 0.01
    temperature: 293
    time_step: 0.5
AL1_train_ConfigurationSelection:
    indices:
        _type: slice
        value:
            start: 0
            step: null
            stop: -1
AL1_train_ConfigurationSelection_1:
    n_configurations: 15
    seed: 1234
AL2_model_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL2_model_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL2_test_ASEGeoOpt:
    data_id: -5
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
AL2_test_ASEGeoOpt+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL2_test_ASEGeoOpt_1:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
AL2_test_ASEMD:
    data_id: -1
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    steps: 100000
    use_momenta: false
AL2_test_ASEMD+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL2_test_ASEMD+thermostat:
    friction: 0.01
    temperature: 293
    time_step: 0.5
AL2_test_ConfigurationSelection:
    indices:
        _type: slice
        value:
            start: 0
            step: null
            stop: -1
AL2_test_ConfigurationSelection_1:
    n_configurations: 5
    seed: 1234
AL2_train_ASEGeoOpt:
    data_id: -5
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
AL2_train_ASEGeoOpt+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL2_train_ASEGeoOpt_1:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
AL2_train_ASEMD:
    data_id: -1
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    steps: 100000
    use_momenta: false
AL2_train_ASEMD+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL2_train_ASEMD+thermostat:
    friction: 0.01
    temperature: 293
    time_step: 0.5
AL2_train_ConfigurationSelection:
    indices:
        _type: slice
        value:
            start: 0
            step: null
            stop: -1
AL2_train_ConfigurationSelection_1:
    n_configurations: 15
    seed: 1234
AL3_model_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL3_model_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL3_test_ASEGeoOpt:
    data_id: -5
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
AL3_test_ASEGeoOpt+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL3_test_ASEGeoOpt_1:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
AL3_test_ASEMD:
    data_id: -1
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    steps: 100000
    use_momenta: false
AL3_test_ASEMD+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL3_test_ASEMD+thermostat:
    friction: 0.01
    temperature: 293
    time_step: 0.5
AL3_test_ConfigurationSelection:
    indices:
        _type: slice
        value:
            start: 0
            step: null
            stop: -1
AL3_test_ConfigurationSelection_1:
    n_configurations: 5
    seed: 1234
AL3_train_ASEGeoOpt:
    data_id: -5
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
AL3_train_ASEGeoOpt+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL3_train_ASEGeoOpt_1:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
AL3_train_ASEMD:
    data_id: -1
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    steps: 100000
    use_momenta: false
AL3_train_ASEMD+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL3_train_ASEMD+thermostat:
    friction: 0.01
    temperature: 293
    time_step: 0.5
AL3_train_ConfigurationSelection:
    indices:
        _type: slice
        value:
            start: 0
            step: null
            stop: -1
AL3_train_ConfigurationSelection_1:
    n_configurations: 15
    seed: 1234
AL4_model_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL4_model_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL4_test_ASEGeoOpt:
    data_id: -5
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
AL4_test_ASEGeoOpt+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL4_test_ASEGeoOpt_1:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
AL4_test_ASEMD:
    data_id: -1
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    steps: 100000
    use_momenta: false
AL4_test_ASEMD+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL4_test_ASEMD+thermostat:
    friction: 0.01
    temperature: 293
    time_step: 0.5
AL4_test_ConfigurationSelection:
    indices:
        _type: slice
        value:
            start: 0
            step: null
            stop: -1
AL4_test_ConfigurationSelection_1:
    n_configurations: 5
    seed: 1234
AL4_train_ASEGeoOpt:
    data_id: -5
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
AL4_train_ASEGeoOpt+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL4_train_ASEGeoOpt_1:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
AL4_train_ASEMD:
    data_id: -1
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    steps: 100000
    use_momenta: false
AL4_train_ASEMD+checker_list+0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL4_train_ASEMD+thermostat:
    friction: 0.01
    temperature: 293
    time_step: 0.5
AL4_train_ConfigurationSelection:
    indices:
        _type: slice
        value:
            start: 0
            step: null
            stop: -1
AL4_train_ConfigurationSelection_1:
    n_configurations: 15
    seed: 1234
GeoOpt_ASEGeoOpt:
    data_id: 0
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.1
GeoOpt_Packmol:
    box: null
    count:
    - 1
    - 1
    data_ids: null
    density: 1210
    tolerance: 2.0
GeoOpt_Packmol_1:
    box: null
    count:
    - 10
    data_ids: null
    density: 1210
    tolerance: 2.0
GeoOpt_SmilesToAtoms:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: CCCCN1C=C[N+](=C1)C
GeoOpt_SmilesToAtoms_1:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: '[B-](F)(F)(F)F'
bootstrap_BoxScale:
    data_id: -1
    num: 30
    start: 0.9
    stop: 2.0
bootstrap_BoxScale+mapping:
    frozen: false
bootstrap_RotateMolecules:
    data_id: -1
    include_original: false
    maximum: 0.17452777777777778
    n_configurations: 15
    seed: 1
bootstrap_TranslateMolecules:
    data_id: -1
    include_original: false
    maximum: 0.3
    n_configurations: 15
    seed: 1
initial_model_ConfigurationSelection:
    n_configurations: 30
    seed: 1234
initial_model_ConfigurationSelection_1:
    indices:
        _type: slice
        value:
            start: 10
            step: null
            stop: null
initial_model_ConfigurationSelection_2:
    n_configurations: 100
    seed: 1234
initial_model_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
initial_model_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
