foundation_model: small
energy_weight: 1.0
forces_weight: 1.0
stress_weight: 1.0
E0s: average
lr: 0.01
scaling: rms_forces_scaling
batch_size: 1
max_num_epochs: 200
ema: true
ema_decay: 0.99
swa: true
start_swa: 100
patience: 50
amsgrad: true
default_dtype: float64
seed: 3
