ensemble:
  name: nvt
  dt: 0.5 # fs time step
  temperature: 315 # K

duration: 100_000 # fs
n_inner: 1000 # compiled inner steps
sampling_rate: 10  # dump interval
buffer_size: 1000
dr_threshold: 0.5 # Neighborlist skin
