n_epochs: 2000
seed: 1
n_models: 2
n_jitted_steps: 8
patience: 500

data:
  batch_size: 1
  scale_method: per_element_force_rms_scale
  shift_method: per_element_regression_shift
  shift_options:
    energy_regularisation: 1.0
  valid_batch_size: 70
loss:
- name: energy
- name: forces
  weight: 4.0
- name: stress
  weight: 0.2

metrics:
- name: energy
  reductions:
  - mae
- name: forces
  reductions:
  - mae
- name: stress
  reductions:
  - mae

model:
  n_basis: 7
  n_radial: 5
  nn:
  - 512
  - 512
  r_max: 6.0
  r_min: 0.7

  b_init: zeros
  emb_init: uniform
  
  calc_stress: true
  use_zbl: false

  descriptor_dtype: fp32
  readout_dtype: fp32
  scale_shift_dtype: fp32

optimizer:
  opt_name: adam
  emb_lr: 0.01
  nn_lr: 0.005
  scale_lr: 0.001
  shift_lr: 0.05
  zbl_lr: 0.001
